INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco A.J.Renner S.A.','654','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco ABC Brasil S.A.','246','www.abcbrasil.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Alfa S.A.','25','www.bancoalfa.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Alvorada S.A.','641','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Arbi S.A.','213','www.arbi.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Azteca do Brasil S.A.','19','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Banerj S.A.','29','www.banerj.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bankpar S.A.','0','www.aexp.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Barclays S.A.','740','www.barclays.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BBM S.A.','107','www.bbmbank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Beg S.A.','31','www.itau.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BGN S.A.','739','www.bgn.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BM&F de Serviços de Liquidação e Custódia S.A','96','www.bmf.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BMG S.A.','318','www.bancobmg.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BNP Paribas Brasil S.A.','752','www.bnpparibas.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Boavista Interatlântico S.A.','248','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bonsucesso S.A.','218','www.bancobonsucesso.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bracce S.A.','65','www.lemon.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bradesco BBI S.A.','36','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bradesco Cartões S.A.','204','www.iamex.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bradesco Financiamentos S.A.','394','www.bmc.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Bradesco S.A.','237','www.bradesco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Brascan S.A.','225','www.bancobrascan.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BRJ S.A.','M15','www.brjbank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BTG Pactual S.A.','208','www.pactual.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco BVA S.A.','44','www.bancobva.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cacique S.A.','263','www.bancocacique.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Caixa Geral - Brasil S.A.','473','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Capital S.A.','412','www.bancocapital.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cargill S.A.','40','www.bancocargill.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Citibank S.A.','745','www.citibank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Citicard S.A.','M08','www.credicardbanco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Clássico S.A.','241','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco CNH Capital S.A.','M19','www.bancocnh.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Comercial e de Investimento Sudameris S.A.','215','www.sudameris.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cooperativo do Brasil S.A. - BANCOOB','756','www.bancoob.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cooperativo Sicredi S.A.','748','www.sicredi.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco CR2 S.A.','75','www.bancocr2.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Credibel S.A.','721','www.credibel.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Credit Agricole Brasil S.A.','222','www.calyon.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Credit Suisse (Brasil) S.A.','505','www.csfb.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cruzeiro do Sul S.A.','229','www.bcsul.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Cédula S.A.','266','www.bancocedula.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco da Amazônia S.A.','3','www.bancoamazonia.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco da China Brasil S.A.','083-3','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Daimlerchrysler S.A.','M21','www.bancodaimlerchrysler.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Daycoval S.A.','707','www.daycoval.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de La Nacion Argentina','300','www.bna.com.ar')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de La Provincia de Buenos Aires','495','www.bapro.com.ar')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de La Republica Oriental del Uruguay','494','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de Lage Landen Brasil S.A.','M06','www.delagelanden.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de Pernambuco S.A. - BANDEPE','24','www.bandepe.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco de Tokyo-Mitsubishi UFJ Brasil S.A.','456','www.btm.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Dibens S.A.','214','www.bancodibens.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Brasil S.A.','001','www.bb.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Estado de Sergipe S.A.','47','www.banese.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Estado do Pará S.A.','37','www.banparanet.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Estado do Piauí S.A. - BEP','39','www.bep.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Estado do Rio Grande do Sul S.A.','41','www.banrisul.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco do Nordeste do Brasil S.A.','4','www.banconordeste.gov.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Fator S.A.','265','www.bancofator.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Fiat S.A.','M03','www.bancofiat.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Fibra S.A.','224','www.bancofibra.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Ficsa S.A.','626','www.ficsa.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Ford S.A.','M18','www.bancoford.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco GE Capital S.A.','233','www.ge.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Gerdau S.A.','734','www.bancogerdau.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco GMAC S.A.','M07','www.bancogm.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Guanabara S.A.','612','www.bcoguan.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Honda S.A.','M22','www.bancohonda.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Ibi S.A. Banco Múltiplo','63','www.ibi.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco IBM S.A.','M11','www.ibm.com/br/financing/')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Industrial do Brasil S.A.','604','www.bancoindustrial.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Industrial e Comercial S.A.','320','www.bicbanco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Indusval S.A.','653','www.indusval.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Intercap S.A.','630','www.intercap.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Intermedium S.A.','077-9','www.intermedium.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Investcred Unibanco S.A.','249','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Itaucred Financiamentos S.A.','M09','www.itaucred.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Itaú BBA S.A.','184','www.itaubba.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco ItaúBank S.A','479','www.itaubank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco J. P. Morgan S.A.','376','www.jpmorgan.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco J. Safra S.A.','74','www.jsafra.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco John Deere S.A.','217','www.johndeere.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco KDB S.A.','76','www.bancokdb.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco KEB do Brasil S.A.','757','www.bancokeb.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Luso Brasileiro S.A.','600','www.lusobrasileiro.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Matone S.A.','212','www.bancomatone.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Maxinvest S.A.','M12','www.bancomaxinvest.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Mercantil do Brasil S.A.','389','www.mercantil.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Modal S.A.','746','www.bancomodal.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Moneo S.A.','M10','www.bancomoneo.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Morada S.A.','738','www.bancomorada.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Morgan Stanley S.A.','66','www.morganstanley.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Máxima S.A.','243','www.bancomaxima.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Opportunity S.A.','45','www.opportunity.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Ourinvest S.A.','M17','www.ourinvest.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Panamericano S.A.','623','www.panamericano.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Paulista S.A.','611','www.bancopaulista.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Pecúnia S.A.','613','www.bancopecunia.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Petra S.A.','094-2','www.personaltrader.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Pine S.A.','643','www.bancopine.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Porto Seguro S.A.','724','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Pottencial S.A.','735','www.pottencial.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Prosper S.A.','638','www.bancoprosper.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco PSA Finance Brasil S.A.','M24','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Rabobank International Brasil S.A.','747','www.rabobank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Randon S.A.','088-4','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Real S.A.','356','www.bancoreal.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Rendimento S.A.','633','www.rendimento.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Ribeirão Preto S.A.','741','www.brp.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Rodobens S.A.','M16','www.rodobens.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Rural Mais S.A.','72','www.rural.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Rural S.A.','453','www.rural.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Safra S.A.','422','www.safra.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Santander (Brasil) S.A.','033','www.santander.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Schahin S.A.','250','www.bancoschahin.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Semear S.A.','743','www.bancosemear.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Simples S.A.','749','www.bancosimples.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Société Générale Brasil S.A.','366','www.sgbrasil.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Sofisa S.A.','637','www.sofisa.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Standard de Investimentos S.A.','12','www.standardbank.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Sumitomo Mitsui Brasileiro S.A.','464','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Topázio S.A.','082-5','www.bancotopazio.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Toyota do Brasil S.A.','M20','www.bancotoyota.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Tricury S.A.','M13','www.tricury.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Triângulo S.A.','634','www.tribanco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Volkswagen S.A.','M14','www.bancovw.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Volvo (Brasil) S.A.','M23','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco Votorantim S.A.','655','www.bancovotorantim.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco VR S.A.','610','www.vr.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banco WestLB do Brasil S.A.','370','www.westlb.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BANESTES S.A. Banco do Estado do Espírito Santo','21','www.banestes.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Banif-Banco Internacional do Funchal (Brasil)S.A.','719','www.banif.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Bank of America Merrill Lynch Banco Múltiplo S.A.','755','www.ml.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BankBoston N.A.','744','www.bankboston.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BB Banco Popular do Brasil S.A.','73','www.bancopopulardobrasil.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BES Investimento do Brasil S.A.-Banco de Investimento','78','www.besinvestimento.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BPN Brasil Banco Múltiplo S.A.','69','www.bpnbrasil.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('BRB - Banco de Brasília S.A.','70','www.brb.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Brickell S.A. Crédito, financiamento e Investimento','092-2','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Caixa Econômica Federal','104','www.caixa.gov.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Citibank N.A.','477','www.citibank.com/brasil')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Concórdia Banco S.A.','081-7','www.concordiabanco.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa Central de Crédito Noroeste Brasileiro Ltda.','097-3','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa Central de Crédito Urbano-CECRED','085-x','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa Central de Economia e Credito Mutuo das Unicreds','099-x','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa Central de Economia e Crédito Mutuo das Unicreds','090-2','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa de Crédito Rural da Região de Mogiana','089-2','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Cooperativa Unicred Central Santa Catarina','087-6','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Credicorol Cooperativa de Crédito Rural','098-1','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Deutsche Bank S.A. - Banco Alemão','487','www.deutsche-bank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Dresdner Bank Brasil S.A. - Banco Múltiplo','751','www.dkib.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Goldman Sachs do Brasil Banco Múltiplo S.A.','64','www.goldmansachs.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Hipercard Banco Múltiplo S.A.','62','www.hipercard.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('HSBC Bank Brasil S.A. - Banco Múltiplo','399','www.hsbc.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('HSBC Finance (Brasil) S.A. - Banco Múltiplo','168','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('ING Bank N.V.','492','www.ing.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Itaú Unibanco Holding S.A.','652','www.itau.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Itaú Unibanco S.A.','341','www.itau.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('JBS Banco S.A.','79','www.bancojbs.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('JPMorgan Chase Bank','488','www.jpmorganchase.com')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Natixis Brasil S.A. Banco Múltiplo','14','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('NBC Bank Brasil S.A. - Banco Múltiplo','753','www.nbcbank.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('OBOE Crédito Financiamento e Investimento S.A.','086-8','-')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Paraná Banco S.A.','254','www.paranabanco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('UNIBANCO - União de Bancos Brasileiros S.A.','409','www.unibanco.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Unicard Banco Múltiplo S.A.','230','www.unicard.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Unicred Central do Rio Grande do Sul','091-4','www.unicred-rs.com.br')
INSERT INTO BANCO(DESCRICAO, NUMERO, SITE) VALUES ('Unicred Norte do Paraná','84','-')