INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQUICULTURA' , 'A')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('INDÚSTRIAS EXTRATIVAS' , 'B')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('INDUÚSTRIAS DE TRANSFORMAÇÃO' , 'C')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ELETRICIDADE E GÁS' , 'D')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO' , 'E')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('CONSTRUÇÃO' , 'F')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('COMÉRCIO REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS' , 'G')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('TRANSPORTE, ARMAZENAGEM E CORREIO' , 'H')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ALOJAMENTO E ALIMENTAÇÃO' , 'I')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('INFORMAÇÃO E COMUNICAÇÃO' , 'J')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS' , 'K')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ATIVIDADES IMOBILIÁRIAS' , 'L')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS' , 'M')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES' , 'N')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL' , 'O')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('EDUCAÇÃO' , 'P')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('SAÚDE HUMANA E SERVIÇOS SOCIAIS' , 'Q')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ARTES, CULTURA, ESPORTE E RECREAÇÃO' , 'R')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('OUTRAS ATIVIDADES DE SERVIÇOS' , 'S')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('SERVIÇOS DOMÉSTICOS' , 'T')

INSERT INTO CLASSIFICACAO(DESCRICAO, SECAO)
VALUES('ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS' , 'U')
