
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo suporte', 'AD', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo master usuário', 'MU', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo vendedor', 'V', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo master vendedor', 'MV', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo usuário comum', 'UC', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo funcionário', 'FR', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo master contador', 'MC', 'S')
INSERT INTO GRUPO(DESCRICAO, TIPO, GESTAO_INTERNA) VALUES('Grupo contabilidade', 'C', 'S')
