INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Nome', 'T',  1, 'S', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Matrícula', 'I',  2, 'S', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'CPF', 'T',  3, 'S', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Data de nascimento', 'D',  4, 'S', null, 'dd/MM/yyyy')

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Data de contratação', 'D',  5, 'S', null, 'dd/MM/yyyy')

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Data de demissão', 'D',  6, 'N', null, 'dd/MM/yyyy')

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Salário', 'I',  7, 'N', ',', null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Email', 'T',  8, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Telefone residencial', 'T',  9, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Telefone celular', 'T',  10, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'CEP', 'T',  11, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Endereco', 'T',  12, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Número', 'T',  13, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Complemento', 'T',  14, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Bairro', 'T',  15, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Cidade', 'T',  16, 'N', null, null)

INSERT INTO LAYOUT_CAMPO(ID_LAYOUT, DESCRICAO, TIPO_DADO, POSICAO_ARQUIVO, OBRIGATORIO, SEPARADOR_CASAS_DECIMAIS, MASCARA_DATA)
VALUES((SELECT ID FROM LAYOUT WHERE DESCRICAO = 'Layout funcionário'), 'Nome da mãe', 'T',  17, 'N', null, null)