
INSERT INTO PERFIL(DESCRICAO, TIPO) VALUES('Suporte', 'AD')
INSERT INTO PERFIL(DESCRICAO, TIPO) VALUES('Vendedor', 'V')
INSERT INTO PERFIL(DESCRICAO, TIPO) VALUES('Master vendedor', 'MV')
INSERT INTO PERFIL(DESCRICAO, TIPO) VALUES('Usuário master', 'UM')
INSERT INTO PERFIL(DESCRICAO, TIPO) VALUES('Usuário comum', 'UC')
INSERT INTO PERFIL (DESCRICAO, TIPO) VALUES('Funcionário', 'FR')
INSERT INTO PERFIL (DESCRICAO, TIPO) VALUES ('Master contabilidade', 'MC')
INSERT INTO PERFIL (DESCRICAO, TIPO) VALUES ('Contabilidade', 'C')