INSERT INTO SECAO_NCM
VALUES('ANIMAIS VIVOS E PRODUTOS DO REINO ANIMAL')

INSERT INTO SECAO_NCM
VALUES('PRODUTOS DO REINO VEGETAL')

INSERT INTO SECAO_NCM
VALUES('GORDURAS E ÓLEOS ANIMAIS OU VEGETAIS; PRODUTOS DA SUA DISSOCIAÇÃO; GORDURAS
ALIMENTARES ELABORADAS; CERAS DE ORIGEM ANIMAL OU VEGETAL')

INSERT INTO SECAO_NCM
VALUES('PRODUTOS DAS INDÚSTRIAS ALIMENTARES; BEBIDAS, LÍQUIDOS ALCOÓLICOS E VINAGRES; TABACO
E SEUS SUCEDÂNEOS MANUFATURADOS')

INSERT INTO SECAO_NCM
VALUES('PRODUTOS MINERAIS')

INSERT INTO SECAO_NCM
VALUES('PRODUTOS DAS INDÚSTRIAS QUÍMICAS OU DAS INDÚSTRIAS CONEXAS')

INSERT INTO SECAO_NCM
VALUES('PLÁSTICOS E SUAS OBRAS; BORRACHA E SUAS OBRAS')

INSERT INTO SECAO_NCM
VALUES('PELES, COUROS, PELES COM PELO E OBRAS DESTAS MATÉRIAS; ARTIGOS DE CORREEIRO OU DE
SELEIRO; ARTIGOS DE VIAGEM, BOLSAS E ARTEFATOS SEMELHANTES; OBRAS DE TRIPA')

INSERT INTO SECAO_NCM
VALUES('MADEIRA, CARVÃO VEGETAL E OBRAS DE MADEIRA; CORTIÇA E SUAS OBRAS; OBRAS DE ESPARTARIA
OU DE CESTARIA')

INSERT INTO SECAO_NCM
VALUES('PASTAS DE MADEIRA OU DE OUTRAS MATÉRIAS FIBROSAS CELULÓSICAS; PAPEL OU CARTÃO PARA
RECICLAR (DESPERDÍCIOS E APARAS); PAPEL OU CARTÃO E SUAS OBRAS')

INSERT INTO SECAO_NCM
VALUES('MATÉRIAS TÊXTEIS E SUAS OBRAS')

INSERT INTO SECAO_NCM
VALUES('CALÇADOS, CHAPÉUS E ARTEFATOS DE USO SEMELHANTE, GUARDA-CHUVAS, GUARDA-SÓIS,
BENGALAS, CHICOTES, E SUAS PARTES; PENAS PREPARADAS E SUAS OBRAS; FLORES ARTIFICIAIS;
OBRAS DE CABELO')

INSERT INTO SECAO_NCM
VALUES('OBRAS DE PEDRA, GESSO, CIMENTO, AMIANTO, MICA OU DE MATÉRIAS SEMELHANTES; PRODUTOS
CERÂMICOS; VIDRO E SUAS OBRAS')

INSERT INTO SECAO_NCM
VALUES('PÉROLAS NATURAIS OU CULTIVADAS, PEDRAS PRECIOSAS OU SEMIPRECIOSAS E SEMELHANTES,
METAIS PRECIOSOS, METAIS FOLHEADOS OU CHAPEADOS DE METAIS PRECIOSOS (PLAQUÊ), E SUAS
OBRAS; BIJUTERIAS; MOEDAS')

INSERT INTO SECAO_NCM
VALUES('METAIS COMUNS E SUAS OBRAS')

INSERT INTO SECAO_NCM
VALUES('MÁQUINAS E APARELHOS, MATERIAL ELÉTRICO, E SUAS PARTES; APARELHOS DE GRAVAÇÃO OU DE
REPRODUÇÃO DE SOM, APARELHOS DE GRAVAÇÃO OU DE REPRODUÇÃO DE IMAGENS E DE SOM EM
TELEVISÃO, E SUAS PARTES E ACESSÓRIOS')

INSERT INTO SECAO_NCM
VALUES('MATERIAL DE TRANSPORTE')

INSERT INTO SECAO_NCM
VALUES('INSTRUMENTOS E APARELHOS DE ÓPTICA, DE FOTOGRAFIA, DE CINEMATOGRAFIA, DE MEDIDA, DE
CONTROLE OU DE PRECISÃO; INSTRUMENTOS E APARELHOS MÉDICO-CIRÚRGICOS; ARTIGOS DE
RELOJOARIA; INSTRUMENTOS MUSICAIS; SUAS PARTES E ACESSÓRIOS')

INSERT INTO SECAO_NCM
VALUES('ARMAS E MUNIÇÕES; SUAS PARTES E ACESSÓRIOS')

INSERT INTO SECAO_NCM
VALUES('MERCADORIAS E PRODUTOS DIVERSOS')

INSERT INTO SECAO_NCM
VALUES('OBJETOS DE ARTE, DE COLEÇÃO E ANTIGUIDADES')