-- TABLES
CREATE TABLE REVINFO ( 
        REVTYPE int identity(1,1) NOT NULL,
        DATA_ATUALIZACAO datetime,
        IP varchar(255),
        REVTSTMP bigint,
        USUARIO varchar(255),
        CONSTRAINT PK_REVINFO PRIMARY KEY CLUSTERED (REVTYPE)
)




CREATE TABLE NCM ( 
	ID int identity(1,1)  NOT NULL,
	CODIGO int NOT NULL,
	DESCRICAO varchar(500) NOT NULL,
	ALIQUOTA_NACIONAL numeric(10,2),
	ALIQUOTA_IMPORTADO numeric(10,2),
	EX int,
	NCM_NBS varchar(1)
)
;

ALTER TABLE NCM ADD CONSTRAINT PK_NCM 
	PRIMARY KEY CLUSTERED (ID)
;

CREATE TABLE BANCO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	NUMERO int NOT NULL
)
;

CREATE TABLE CATEGORIA ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	TIPO varchar(1)
)
;

CREATE TABLE CENTRO_CUSTO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL
)
;

CREATE TABLE CIDADE ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	ID_UF int NOT NULL
)
;

CREATE TABLE CLIENTE ( 
	ID int identity(1,1)  NOT NULL,
	ID_CIDADE int,
	NOME varchar(200),
	TIPO varchar(2),
	CPF_CNPJ varchar(20) NOT NULL,
	RAZAO_SOCIAL varchar(200),
	TEM_INSCRICAO_ESTADUAL varchar(1),
	INSCRICAO_ESTADUAL varchar(50),
	INDICADOR_INSCRICAO_ESTADUAL varchar(2),
	INSCRICAO_MUNICIPAL varchar(50),
	OPTA_SIMPLES varchar(1),
	EMAIL varchar(50),
	TELEFONE_COMERCIAL varchar(50),
	TELEFONE_RESIDENCIAL varchar(50),
	TELEFONE_CELULAR varchar(50),
	CEP varchar(15),
	ENDERECO varchar(2000),
	NUMERO varchar(50),
	COMPLEMENTO varchar(200)
)
;

CREATE TABLE CLIENTE_CONTATO ( 
	ID int identity(1,1)  NOT NULL,
	ID_CLIENTE int NOT NULL,
	NOME varchar(200),
	EMAIL varchar(50),
	TELEFONE varchar(50),
	CARGO varchar(50)
)
;

CREATE TABLE COMPRA ( 
	ID int identity(1,1)  NOT NULL,
	ID_FORNECEDOR int NOT NULL,
	ID_NATUREZA_OPERACAO int,
	ID_TRANSPORTADORA int,
	NUMERO_PEDIDO varchar(10) NOT NULL,
	SITUACAO varchar(1),
	DATA_PEDIDO datetime,
	PRAZO_RECEBIMENTO datetime,
	FORMA_PAGAMENTO varchar(1) NOT NULL,
	NUM_PARCELA int NOT NULL,
	OBSERVACAO varchar(500),
	SERIE varchar(50),
	NUMERO_NF varchar(50),
	NUM_COMPRA varchar(50),
	PAGAR_FRETE varchar(1),
	VALOR_FRETE numeric(10,2),
	VALOR_DESCONTO numeric(10,2),
	DATA_COMPRA datetime NOT NULL
)
;

CREATE TABLE COMPRA_PRODUTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_COMPRA int NOT NULL,
	ID_PRODUTO int NOT NULL,
	QUANTIDADE numeric(10,2) NOT NULL
)
;

CREATE TABLE CONTA_BANCARIA ( 
	ID int identity(1,1)  NOT NULL,
	ID_BANCO int NOT NULL,
	DESCRICAO varchar(200),
	AGENCIA varchar(50),
	SALDO_INICIAL numeric(10,2),
	DATA_SALDO datetime,
	TIPO_CONTA varchar(1)
)
;

CREATE TABLE CONTA_PAGAR ( 
	ID int identity(1,1)  NOT NULL,
	ID_FORNECEDOR int NOT NULL,
	ID_DOCUMENTO int,
	ID_COMPRA int,
	ID_CENTRO_CUSTO int,
	ID_CATEGORIA int NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	DATA_VENCIMENTO datetime,
	NUM_PARCELA int NOT NULL,
	VALOR_TOTAL numeric(10,2) NOT NULL,
	SITUACAO varchar(2),
	MULTA_ATRASO numeric(10,2),
	JUROS numeric(10,2),
	ENCARGOS numeric(10,2),
	OBSERVACAO varchar(200)
)
;

CREATE TABLE CONTA_PAGAR_PAGAMENTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_PAGAR int NOT NULL,
	ID_TIPO_PAGAMENTO int NOT NULL,
	FORMA_PAGAMENTO varchar(100),
	VALOR numeric(10,2)
)
;

CREATE TABLE CONTA_PAGAR_PARCELA ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_PAGAR int NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	ID_DOCUMENTO int,
	NUM_PARCELA int,
	VALOR numeric(10,2) NOT NULL,
	DATA_VENCIMENTO datetime,
	DATA_PAGAMENTO datetime,
	SITUACAO varchar(2) NOT NULL,
	MULTA numeric(10,2),
	JUROS numeric(10,2),
	ENCARGOS numeric(10,2)
)
;

CREATE TABLE CONTA_PAGAR_PARCELA_PARCIAL ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_PAGAR_PARCELA int NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	ID_DOCUMENTO int,
	VALOR numeric(10,2) NOT NULL,
	SITUACAO varchar(2),
	DATA_PAGAMENTO datetime,
	DATA_VENCIMENTO datetime,
	JUROS numeric(10,2),
	MULTA numeric(10,2),
	ENCARGOS numeric(10,2)
)
;

CREATE TABLE CONTA_RECEBER ( 
	ID int identity(1,1)  NOT NULL,
	ID_CLIENTE int NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	ID_CENTRO_CUSTO int,
	ID_DOCUMENTO int,
	ID_VENDA int,
	ID_CATEGORIA int NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	SITUACAO varchar(2) NOT NULL,
	DATA_VENCIMENTO datetime NOT NULL,
	VALOR numeric(10,2),
	VALOR_RECEBIDO numeric(10,2) NOT NULL,
	DATA_RECEBIMENTO datetime,
	DESCONTO numeric(10,2),
	JUROS numeric(10,2),
	OUTROS_CUSTOS numeric(10,2),
	OBSERVACAO varchar(500)
)
;

CREATE TABLE CONTA_RECEBER_PAGAMENTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_RECEBER int NOT NULL,
	ID_TIPO_PAGAMENTO int NOT NULL,
	VALOR numeric(10,2) NOT NULL
)
;

CREATE TABLE CONTA_RECEBER_PARCELA ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_RECEBER int NOT NULL,
	ID_DOCUMENTO int,
	ID_CONTA_BANCARIA int,
	SITUACAO varchar(1),
	DATA_VENCIMENTO datetime NOT NULL,
	VALOR_PARCELA numeric(10,2) NOT NULL,
	OBSERVACAO varchar(50),
	DATA_RECEBIMENTO datetime,
	VALOR_RECEBIDO numeric(10,2),
	DESCONTO numeric(10,2),
	JUROS numeric(10,2)
)
;

CREATE TABLE CONTA_RECEBER_PARCELA_PARCIAL ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_RECEBER_PARCELA int NOT NULL,
	ID_DOCUMENTO int,
	ID_CONTA_BANCARIA int,
	DATA_PAGAMENTO datetime,
	VALOR_PAGO numeric(10,2)
)
;

CREATE TABLE DOCUMENTO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200)
)
;

CREATE TABLE DOCUMENTO_ANEXO ( 
	ID int identity(1,1)  NOT NULL,
	ID_DOCUMENTO int NOT NULL,
	ARQUIVO varbinary(3000) NOT NULL
)
;

CREATE TABLE ESTOQUE ( 
	ID int identity(1,1)  NOT NULL,
	ID_COMPRA_PRODUTO int,
	ID_VENDA_PRODUTO int,
	ID_PRODUTO int,
	DATA datetime NOT NULL,
	QUANTIDADE numeric(10,2) NOT NULL,
	TIPO_OPERACAO varchar(2) NOT NULL,
	SALDO_ANTERIOR numeric(10,2) NOT NULL,
	SALDO numeric(10,2)
)
;

CREATE TABLE EXTRATO_CONTA_CORRENTE ( 
	ID int identity(1,1)  NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	SALDO_ANTERIOR numeric(10,2) NOT NULL,
	SALDO numeric(10,2) NOT NULL,
	TIPO varchar(1),
	ID_CONTA_PAGAR_PARCELA int,
	ID_CONTA_PAGAR_PARCELA_PARCIAL int,
	ID_CONTA_RECEBER_PARCELA int,
	ID_CONTA_RECEBER_PARCELA_PARCIAL int
)
;

CREATE TABLE FORNECEDOR ( 
	ID int identity(1,1)  NOT NULL,
	ID_CIDADE int,
	TIPO_PESSOA varchar(1) NOT NULL,
	CPF_CNPJ varchar(30) NOT NULL,
	RAZAO_SOCIAL varchar(50),
	INSCRICAO_ESTADUAL varchar(50),
	INSCRICAO_MUNICIPAL varchar(50),
	CEP varchar(20),
	ENDERECO varchar(200),
	NUMERO varchar(10),
	BAIRRO varchar(50),
	COMPLEMENTO varchar(100),
	FONE_COMERCIAL varchar(50),
	EMAIL varchar(50),
	FONE_RESIDENCIAL varchar(50),
	CONTATO varchar(50),
	CELULAR varchar(50),
	OBSERVACAO varchar(500)
)
;

CREATE TABLE FORNECEDOR_CONTATO ( 
	ID int identity(1,1)  NOT NULL,
	ID_FORNECEDOR int NOT NULL,
	NOME varchar(200),
	EMAIL varchar(50),
	TELEFONE varchar(50),
	CARGO varchar(50)
)
;

CREATE TABLE FORNECEDOR_PRODUTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_FORNECEDOR int NOT NULL,
	ID_PRODUTO int NOT NULL,
	ATIVO varchar(2) NOT NULL
)
;

CREATE TABLE GRUPO ( 
	ID int identity(1,1)  NOT NULL,
	ID_USUARIO_RESPONSAVEL int,
	DESCRICAO varchar(200) NOT NULL,
	TIPO varchar(2) NOT NULL,
	GESTAO_INTERNA varchar(1) NOT NULL
)
;

CREATE TABLE NATUREZA_OPERACAO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL
)
;

CREATE TABLE NF ( 
	ID int identity(1,1)  NOT NULL,
	ID_CLIENTE int NOT NULL,
	DATA_GERACAO datetime NOT NULL
)
;

CREATE TABLE PERFIL ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200),
	TIPO varchar(2) NOT NULL
)
;

CREATE TABLE PERMISSAO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	DESCRICAO_DETALHADA varchar(500)
)
;

CREATE TABLE PERMISSAO_PERFIL ( 
	ID int identity(1,1)  NOT NULL,
	ID_PERFIL int NOT NULL,
	ID_PERMISSAO int NOT NULL
)
;

CREATE TABLE PLANO_CONTA ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	ID_CONTA_PAI int,
	TIPO varchar(2) NOT NULL
)
;

CREATE TABLE PRODUTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_CATEGORIA_PRODUTO int NOT NULL,
	ID_UNIDADE_MEDIDA int,
	DESCRICAO varchar(200) NOT NULL,
	VALOR_VENDA numeric(10,2),
	CODIGO varchar(20),
	VALOR_CUSTO numeric(10,2),
	ESTOQUE_DISPONIVEL numeric(10,2),
	CODIGO_BARRAS varchar(50),
	NCM varchar(100),
	PESO_LIQUIDO numeric(10,2),
	PESO_BRUTO numeric(10,2)
)
;

CREATE TABLE PRODUTO_CATEGORIA ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(500) NOT NULL
)
;

CREATE TABLE SERVICO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL
)
;

CREATE TABLE TIPO_PAGAMENTO ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200) NOT NULL
)
;

CREATE TABLE TRANSPORTADORA ( 
	ID int identity(1,1)  NOT NULL,
	ID_CIDADE int,
	DESCRICAO varchar(200),
	CNPJ varchar(20),
	INSCRICAO_ESTADUAL varchar(50),
	INSCRICAO_MUNICIPAL varchar(50),
	ISENTO_ICMS varchar(1) NOT NULL,
	CEP varchar(20),
	ENDERECO varchar(200),
	NUMERO varchar(10),
	BAIRRO varchar(50),
	COMPLEMENTO varchar(100),
	FONE_COMERCIAL varchar(50),
	EMAIL varchar(50),
	FONE_RESIDENCIAL varchar(50),
	CONTATO varchar(50),
	CELULAR varchar(50),
	OBSERVACAO varchar(50),
	VALOR_FRETE numeric(10,2),
	XML_NF varchar(2000)
)
;

CREATE TABLE UF ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(2),
	NOME_COMPLETO varchar(50)
)
;

CREATE TABLE UNIDADE_MEDIDA ( 
	ID int identity(1,1)  NOT NULL,
	DESCRICAO varchar(200)
)
;

CREATE TABLE USUARIO ( 
	ID int identity(1,1)  NOT NULL,
	ID_PERFIL int NOT NULL,
	NOME varchar(200) NOT NULL,
	LOGIN varchar(50) NOT NULL,
	CONTA_EXPIRADA varchar(1) NOT NULL,
	CONTA_BLOQUEADA varchar(1) NOT NULL,
	FOTO varbinary(50),
	ADMINISTRATOR bit NOT NULL,
	EMAIL varchar(255),
	TEMA varchar(20)
)
;

CREATE TABLE USUARIO_GRUPO ( 
	ID int identity(1,1)  NOT NULL,
	ID_USUARIO int NOT NULL,
	ID_GRUPO int NOT NULL
)
;

CREATE TABLE USUARIO_GRUPO_PERMISSAO ( 
	ID int identity(1,1)  NOT NULL,
	ID_GRUPO int NOT NULL,
	ID_PERMISSAO int NOT NULL
)
;

CREATE TABLE USUARIO_PERMISSAO ( 
	ID int identity(1,1)  NOT NULL,
	ID_USUARIO int NOT NULL,
	ID_PERMISSAO int NOT NULL
)
;

CREATE TABLE VENDA ( 
	ID int identity(1,1)  NOT NULL,
	ID_CLIENTE int NOT NULL,
	ID_DOCUMENTO int,
	ID_USUARIO_VENDEDOR int,
	DATA_VENCIMENTO datetime NOT NULL,
	VALOR numeric(10,2) NOT NULL,
	SITUACAO varchar(2) NOT NULL,
	NUM_PARCELA int NOT NULL,
	DESCONTO numeric(10,2),
	VALOR_FRETE numeric(10,2),
	FORMA_PAGAMENTO varchar(2000),
	OBSERVACAO varchar(2000)
)
;

CREATE TABLE VENDA_PARCELA ( 
	ID int identity(1,1)  NOT NULL,
	ID_VENDA int NOT NULL,
	ID_CONTA_BANCARIA int,
	ID_DOCUMENTO int,
	NUM_PARCELA int,
	VALOR numeric(10,2) NOT NULL,
	SITUACAO varchar(2) NOT NULL,
	DATA_VENCIMENTO datetime NOT NULL,
	DATA_RECEBIMENTO datetime,
	VALOR_RECEBIDO numeric(10,2),
	VALOR_JUROS numeric(10,2),
	VALOR_MULTA numeric(10,2),
	ENCARGOS numeric(10,2)
)
;

CREATE TABLE VENDA_PARCELA_BAIXA ( 
	ID int identity(1,1)  NOT NULL,
	ID_VENDA_PARCELA int NOT NULL,
	ID_CONTA_BANCARIA int NOT NULL,
	ID_DOCUMENTO int,
	DATA_RECEBIMENTO datetime NOT NULL,
	VALOR_RECEBIDO numeric(10,2) NOT NULL,
	VALOR_JUROS numeric(10,2),
	VALOR_MULTA numeric(10,2),
	ENCARGOS numeric(10,2)
)
;

CREATE TABLE VENDA_PRODUTO ( 
	ID int identity(1,1)  NOT NULL,
	ID_VENDA int NOT NULL,
	ID_PRODUTO int NOT NULL,
	QUANTIDADE numeric(10,2) NOT NULL
)
;


ALTER TABLE BANCO ADD CONSTRAINT PK_BANCO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CENTRO_CUSTO ADD CONSTRAINT PK_CENTRO_CUSTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CIDADE ADD CONSTRAINT PK_CIDADE 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CLIENTE_CONTATO ADD CONSTRAINT PK_CLIENTE_CONTATO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE COMPRA_PRODUTO ADD CONSTRAINT PK_COMPRA_PRODUTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_BANCARIA ADD CONSTRAINT PK_CONTA_BANCARIA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT PK_CONTA_PAGAR 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_PAGAR_PAGAMENTO ADD CONSTRAINT PK_CONTA_PAGAR_PAGAMENTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA ADD CONSTRAINT PK_CONTA_PAGAR_PARCELA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL ADD CONSTRAINT PK_CONTA_PAGAR_PARCELA_PARCIAL 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT PK_CONTA_RECEBER 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_RECEBER_PAGAMENTO ADD CONSTRAINT PK_CONTA_RECEBER_PAGAMENTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA ADD CONSTRAINT PK_CONTA_RECEBER_PARCELA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL ADD CONSTRAINT PK_CONTA_RECEBER_PARCELA_PARCIAL 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE DOCUMENTO ADD CONSTRAINT PK_DOCUMENTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE DOCUMENTO_ANEXO ADD CONSTRAINT PK_DOCUMENTO_ANEXO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE ESTOQUE ADD CONSTRAINT PK_ESTOQUE 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT PK_CONTA_CORRENTE 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE FORNECEDOR_CONTATO ADD CONSTRAINT PK_FORNECEDOR_CONTATO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE FORNECEDOR_PRODUTO ADD CONSTRAINT PK_FORNECEDOR_PRODUTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE GRUPO ADD CONSTRAINT PK_GRUPO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE NATUREZA_OPERACAO ADD CONSTRAINT PK_NATUREZA_OPERACAO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE NF ADD CONSTRAINT PK_NF 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PERFIL ADD CONSTRAINT PK_PERFIL 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PERMISSAO ADD CONSTRAINT PK_PERMISSAO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PERMISSAO_PERFIL ADD CONSTRAINT PK_PERMISSAO_PERFIL 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PLANO_CONTA ADD CONSTRAINT PK_PLANO_CONTA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE PRODUTO_CATEGORIA ADD CONSTRAINT PK_PRODUTO_CATEGORIA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE SERVICO ADD CONSTRAINT PK_SERVICO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TIPO_PAGAMENTO ADD CONSTRAINT PK_TIPO_PAGAMENTO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE TRANSPORTADORA ADD CONSTRAINT PK_TRANSPORTADORA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE UF ADD CONSTRAINT PK_UF 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE UNIDADE_MEDIDA ADD CONSTRAINT PK_UNIDADE_MEDIDA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE USUARIO ADD CONSTRAINT PK_VENDEDOR 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE USUARIO_GRUPO ADD CONSTRAINT PK_USUARIO_GRUPO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE USUARIO_GRUPO_PERMISSAO ADD CONSTRAINT PK_USUARIO_GRUPO_PERMISSAO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE USUARIO_PERMISSAO ADD CONSTRAINT PK_USUARIO_PERMISSAO 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE VENDA_PARCELA ADD CONSTRAINT PK_VENDA_PARCELA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE VENDA_PARCELA_BAIXA ADD CONSTRAINT PK_VENDA_PARCELA_BAIXA 
	PRIMARY KEY CLUSTERED (ID)
;

ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT PK_VENDA_PRODUTO 
	PRIMARY KEY CLUSTERED (ID)
;




ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_UF 
	FOREIGN KEY (ID_UF) REFERENCES UF (ID)
;

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_CIDADE 
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID)
;

ALTER TABLE CLIENTE_CONTATO ADD CONSTRAINT FK_CLIENTE_CONTATO_CLIENTE 
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
;

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_FORNECEDOR 
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID)
;

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_NATUREZA_OPERACAO 
	FOREIGN KEY (ID_NATUREZA_OPERACAO) REFERENCES NATUREZA_OPERACAO (ID)
;

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_TRANSPORTADORA 
	FOREIGN KEY (ID_TRANSPORTADORA) REFERENCES TRANSPORTADORA (ID)
;

ALTER TABLE COMPRA_PRODUTO ADD CONSTRAINT FK_COMPRA_PRODUTO_PRODUTO 
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
;

ALTER TABLE CONTA_BANCARIA ADD CONSTRAINT FK_CONTA_BANCARIA_BANCO 
	FOREIGN KEY (ID_BANCO) REFERENCES BANCO (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_CATEGORIA 
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_CENTRO_CUSTO 
	FOREIGN KEY (ID_CENTRO_CUSTO) REFERENCES CENTRO_CUSTO (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE CONTA_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_FORNECEDOR 
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID)
;

ALTER TABLE CONTA_PAGAR_PAGAMENTO ADD CONSTRAINT FK_CONTA_PAGAR_PAGAMENTO_CONTA_PAGAR 
	FOREIGN KEY (ID_CONTA_PAGAR) REFERENCES CONTA_PAGAR (ID)
;

ALTER TABLE CONTA_PAGAR_PAGAMENTO ADD CONSTRAINT FK_CONTA_PAGAR_PAGAMENTO_TIPO_PAGAMENTO 
	FOREIGN KEY (ID_TIPO_PAGAMENTO) REFERENCES TIPO_PAGAMENTO (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_CONTA_PAGAR 
	FOREIGN KEY (ID_CONTA_PAGAR) REFERENCES CONTA_PAGAR (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_PARCIAL_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_PARCIAL_CONTA_PAGAR_PARCELA 
	FOREIGN KEY (ID_CONTA_PAGAR_PARCELA) REFERENCES CONTA_PAGAR_PARCELA (ID)
;

ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_PAGAR_PARCELA_PARCIAL_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_CATEGORIA 
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_CENTRO_CUSTO 
	FOREIGN KEY (ID_CENTRO_CUSTO) REFERENCES CENTRO_CUSTO (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_CLIENTE 
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE CONTA_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_VENDA 
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID)
;

ALTER TABLE CONTA_RECEBER_PAGAMENTO ADD CONSTRAINT FK_CONTA_RECEBER_PAGAMENTO_CONTA_RECEBER 
	FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES CONTA_RECEBER (ID)
;

ALTER TABLE CONTA_RECEBER_PAGAMENTO ADD CONSTRAINT FK_CONTA_RECEBER_PAGAMENTO_TIPO_PAGAMENTO 
	FOREIGN KEY (ID_TIPO_PAGAMENTO) REFERENCES TIPO_PAGAMENTO (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_CONTA_RECEBER 
	FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES CONTA_RECEBER (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_PARCIAL_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_PARCIAL_CONTA_RECEBER_PARCELA 
	FOREIGN KEY (ID_CONTA_RECEBER_PARCELA) REFERENCES CONTA_RECEBER_PARCELA (ID)
;

ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL ADD CONSTRAINT FK_CONTA_RECEBER_PARCELA_PARCIAL_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE DOCUMENTO_ANEXO ADD CONSTRAINT FK_DOCUMENTO_ANEXO_DOCUMENTO 
	FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO (ID)
;

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_COMPRA_PRODUTO 
	FOREIGN KEY (ID_COMPRA_PRODUTO) REFERENCES COMPRA_PRODUTO (ID)
;

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_PRODUTO 
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
;

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_VENDA_PRODUTO 
	FOREIGN KEY (ID_VENDA_PRODUTO) REFERENCES VENDA_PRODUTO (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT FK_CONTA_CORRENTE_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT FK_EXTRATO_CONTA_CORRENTE_CONTA_PAGAR_PARCELA 
	FOREIGN KEY (ID_CONTA_PAGAR_PARCELA) REFERENCES CONTA_PAGAR_PARCELA (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT FK_EXTRATO_CONTA_CORRENTE_CONTA_PAGAR_PARCELA_PARCIAL 
	FOREIGN KEY (ID_CONTA_PAGAR_PARCELA_PARCIAL) REFERENCES CONTA_PAGAR_PARCELA_PARCIAL (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT FK_EXTRATO_CONTA_CORRENTE_CONTA_RECEBER_PARCELA 
	FOREIGN KEY (ID_CONTA_RECEBER_PARCELA) REFERENCES CONTA_RECEBER_PARCELA (ID)
;

ALTER TABLE EXTRATO_CONTA_CORRENTE ADD CONSTRAINT FK_EXTRATO_CONTA_CORRENTE_CONTA_RECEBER_PARCELA_PARCIAL 
	FOREIGN KEY (ID_CONTA_RECEBER_PARCELA_PARCIAL) REFERENCES CONTA_RECEBER_PARCELA_PARCIAL (ID)
;

ALTER TABLE FORNECEDOR ADD CONSTRAINT FK_FORNECEDOR_CIDADE 
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID)
;

ALTER TABLE FORNECEDOR_CONTATO ADD CONSTRAINT FK_FORNECEDOR_CONTATO_FORNECEDOR 
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID)
;

ALTER TABLE FORNECEDOR_PRODUTO ADD CONSTRAINT FK_FORNECEDOR_PRODUTO_FORNECEDOR 
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (ID)
;

ALTER TABLE FORNECEDOR_PRODUTO ADD CONSTRAINT FK_FORNECEDOR_PRODUTO_PRODUTO 
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
;

ALTER TABLE GRUPO ADD CONSTRAINT FK_GRUPO_USUARIO 
	FOREIGN KEY (ID_USUARIO_RESPONSAVEL) REFERENCES USUARIO (ID)
;

ALTER TABLE PERMISSAO_PERFIL ADD CONSTRAINT FK_PERMISSAO_PERFIL_PERFIL 
	FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID)
;

ALTER TABLE PLANO_CONTA ADD CONSTRAINT FK_PLANO_CONTA_PLANO_CONTA 
	FOREIGN KEY (ID_CONTA_PAI) REFERENCES PLANO_CONTA (ID)
;

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_PRODUTO_CATEGORIA 
	FOREIGN KEY (ID_CATEGORIA_PRODUTO) REFERENCES PRODUTO_CATEGORIA (ID)
;

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_UNIDADE_MEDIDA 
	FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA (ID)
;

ALTER TABLE TRANSPORTADORA ADD CONSTRAINT FK_TRANSPORTADORA_CIDADE 
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID)
;

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PERFIL 
	FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID)
;

ALTER TABLE USUARIO_GRUPO ADD CONSTRAINT FK_USUARIO_GRUPO_GRUPO 
	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID)
;

ALTER TABLE USUARIO_GRUPO ADD CONSTRAINT FK_USUARIO_GRUPO_USUARIO 
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
;

ALTER TABLE USUARIO_GRUPO_PERMISSAO ADD CONSTRAINT FK_USUARIO_GRUPO_PERMISSAO_GRUPO 
	FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID)
;

ALTER TABLE USUARIO_GRUPO_PERMISSAO ADD CONSTRAINT FK_USUARIO_GRUPO_PERMISSAO_PERMISSAO 
	FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO (ID)
;

ALTER TABLE USUARIO_PERMISSAO ADD CONSTRAINT FK_USUARIO_PERMISSAO_PERMISSAO 
	FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO (ID)
;

ALTER TABLE USUARIO_PERMISSAO ADD CONSTRAINT FK_USUARIO_PERMISSAO_USUARIO 
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
;

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_CLIENTE 
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
;

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_USUARIO 
	FOREIGN KEY (ID_USUARIO_VENDEDOR) REFERENCES USUARIO (ID)
;

ALTER TABLE VENDA_PARCELA ADD CONSTRAINT FK_VENDA_PARCELA_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE VENDA_PARCELA ADD CONSTRAINT FK_VENDA_PARCELA_VENDA 
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID)
;

ALTER TABLE VENDA_PARCELA_BAIXA ADD CONSTRAINT FK_VENDA_PARCELA_BAIXA_CONTA_BANCARIA 
	FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES CONTA_BANCARIA (ID)
;

ALTER TABLE VENDA_PARCELA_BAIXA ADD CONSTRAINT FK_VENDA_PARCELA_BAIXA_VENDA_PARCELA 
	FOREIGN KEY (ID_VENDA_PARCELA) REFERENCES VENDA_PARCELA (ID)
;

ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT FK_VENDA_PRODUTO_PRODUTO 
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
;

ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT FK_VENDA_PRODUTO_VENDA 
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID)
;



-- AUDITORIA
CREATE TABLE VENDA_PRODUTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	QUANTIDADE int NULL,
	ID_PRODUTO int NULL,
	ID_VENDA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE VENDA_PRODUTO_AUD  WITH CHECK ADD  CONSTRAINT FKm0tphb6t0fnnsuvertl8779ou FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

CREATE TABLE VENDA_PARCELA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_RECEBIMENTO datetime2(7) NULL,
	DATA_VENCIMENTO datetime2(7) NULL,
	ENCARGOS float NULL,
	NUM_PARCELA int NULL,
	SITUACAO varchar(2) NULL,
	VALOR_JUROS float NULL,
	VALOR_MULTA float NULL,
	VALOR_RECEBIDO float NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_DOCUMENTO int NULL,
	ID_VENDA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE VENDA_PARCELA_AUD  WITH CHECK ADD  CONSTRAINT FK10ccnik1rtv4sd4cha0n8v6uq FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


CREATE TABLE VENDA_PARCELA_BAIXA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_RECEBIMENTO datetime2(7) NULL,
	ENCARS float NULL,
	VALOR_JUROS float NULL,
	VALOR_MULTA float NULL,
	VALOR_RECEBIDO float NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_DOCUMENTO int NULL,
	ID_VENDA_PARCELA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE VENDA_PARCELA_BAIXA_AUD  WITH CHECK ADD  CONSTRAINT FKm1seqtfouc7s8jjkxhegjh5rp FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)



CREATE TABLE VENDA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_VENCIMENTO datetime2(7) NULL,
	DESCONTO float NULL,
	FORMA_PAGAMENTO varchar(2000) NULL,
	NUM_PARCELA int NULL,
	OBSERVACAO varchar(2000) NULL,
	SITUACAO varchar(2) NULL,
	VALOR float NULL,
	VALOR_FRETE float NULL,
	ID_CLIENTE int NULL,
	ID_DOCUMENTO int NULL,
	ID_USUARIO_VENDEDOR int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE VENDA_AUD  WITH CHECK ADD  CONSTRAINT FKi732sx3yp194tx2ak4sewxpa4 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


CREATE TABLE USUARIO_PERMISSAO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ID_PERMISSAO int NULL,
	ID_USUARIO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)
ALTER TABLE USUARIO_PERMISSAO_AUD  WITH CHECK ADD  CONSTRAINT FKa1koxq7emw5j7647r4vgpm0sr FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


CREATE TABLE USUARIO_GRUPO_PERMISSAO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ID_GRUPO int NULL,
	ID_PERMISSAO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE USUARIO_GRUPO_PERMISSAO_AUD  WITH CHECK ADD  CONSTRAINT FKn80hnb5va00pl5pndbdgxik0u FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


CREATE TABLE USUARIO_GRUPO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ID_GRUPO int NULL,
	ID_USUARIO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)
ALTER TABLE USUARIO_GRUPO_AUD  WITH CHECK ADD  CONSTRAINT FKr02tiruaelp5srb5elkm22sjm FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)



CREATE TABLE USUARIO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ADMINISTRATOR bit NULL,
	CONTA_BLOQUEADA varchar(255) NULL,
	CONTA_EXPIRADA varchar(255) NULL,
	EMAIL varchar(255) NULL,
	FOTO varbinary(max) NULL,
	LOGIN varchar(255) NULL,
	NOME varchar(255) NULL,
	TEMA varchar(255) NULL,
	ID_PERFIL int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE USUARIO_AUD  WITH CHECK ADD  CONSTRAINT FKi5jkgk68uqh8p08xn9cjr09t2 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


CREATE TABLE UNIDADE_MEDIDA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE UNIDADE_MEDIDA_AUD  WITH CHECK ADD  CONSTRAINT FKoyi3dhxurlb9jl9l5rd4y10i4 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

ALTER TABLE UNIDADE_MEDIDA_AUD CHECK CONSTRAINT FKoyi3dhxurlb9jl9l5rd4y10i4


CREATE TABLE UF_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	NOME_COMPLETO varchar(50) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE UF_AUD  WITH CHECK ADD  CONSTRAINT FKcudjlrix3maim7093sqlpx5hi FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE UF_AUD CHECK CONSTRAINT FKcudjlrix3maim7093sqlpx5hi

CREATE TABLE TRANSPORTADORA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	BAIRRO varchar(50) NULL,
	CELULAR varchar(50) NULL,
	CEP varchar(20) NULL,
	CNPJ varchar(200) NULL,
	COMPLEMENTO varchar(100) NULL,
	CONTATO varchar(50) NULL,
	DESCRICAO varchar(200) NULL,
	EMAIL varchar(50) NULL,
	ENDERECO varchar(200) NULL,
	FONE_COMERCIAL varchar(50) NULL,
	FONE_RESIDENCIAL varchar(50) NULL,
	INSCRICAO_ESTADUAL varchar(50) NULL,
	INSCRICAO_MUNICIPAL varchar(50) NULL,
	ISENTO_ICMS varchar(1) NULL,
	NUMERO varchar(10) NULL,
	OBSERVACAO varchar(50) NULL,
	VALOR_FRETE float NULL,
	XML_NF varchar(2000) NULL,
	ID_CIDADE int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE TRANSPORTADORA_AUD  WITH CHECK ADD  CONSTRAINT FKmy6t0tf5mq141g21vuh523wqt FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE TRANSPORTADORA_AUD CHECK CONSTRAINT FKmy6t0tf5mq141g21vuh523wqt


CREATE TABLE TIPO_PAGAMENTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE TIPO_PAGAMENTO_AUD  WITH CHECK ADD  CONSTRAINT FK36lubun3x7pxxqmivyq1p665n FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE TIPO_PAGAMENTO_AUD CHECK CONSTRAINT FK36lubun3x7pxxqmivyq1p665n


CREATE TABLE SERVICO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE SERVICO_AUD  WITH CHECK ADD  CONSTRAINT FKke27ajniadtsoqlk8ns3dymfy FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE SERVICO_AUD CHECK CONSTRAINT FKke27ajniadtsoqlk8ns3dymfy



CREATE TABLE PRODUTO_CATERIA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE PRODUTO_CATERIA_AUD  WITH CHECK ADD  CONSTRAINT FKagc1pjjs6275nmemkkxirpv17 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

ALTER TABLE PRODUTO_CATERIA_AUD CHECK CONSTRAINT FKagc1pjjs6275nmemkkxirpv17


CREATE TABLE PRODUTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CODI varchar(255) NULL,
	CODI_BARRA varchar(255) NULL,
	DESCRICAO varchar(200) NULL,
	ESTOQUE_DISPONIVEL float NULL,
	NCM varchar(255) NULL,
	PESO_BRUTO float NULL,
	PESO_LIQUIDO float NULL,
	VALOR_CUSTO float NULL,
	VALOR_VENDA float NULL,
	ID_PRODUTO_CATERIA int NULL,
	ID_UNIDADE_MEDIDA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE PRODUTO_AUD  WITH CHECK ADD  CONSTRAINT FKt8bsecp5jjg71dmjismy3rd62 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

ALTER TABLE PRODUTO_AUD CHECK CONSTRAINT FKt8bsecp5jjg71dmjismy3rd62


CREATE TABLE PLANO_CONTA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	TIPO varchar(2) NULL,
	ID_CONTA_PAI int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE PLANO_CONTA_AUD  WITH CHECK ADD  CONSTRAINT FKp0j7aonuxobq4uorab09bb728 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE PLANO_CONTA_AUD CHECK CONSTRAINT FKp0j7aonuxobq4uorab09bb728


CREATE TABLE PERMISSAO_PERFIL_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ID_PERFIL int NULL,
	ID_PERMISSAO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE PERMISSAO_PERFIL_AUD  WITH CHECK ADD  CONSTRAINT FKlq1pxwyitkjjwgwunwsiwu4yv FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE PERMISSAO_PERFIL_AUD CHECK CONSTRAINT FKlq1pxwyitkjjwgwunwsiwu4yv



CREATE TABLE PERMISSAO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
	DESCRICAO_DETALHADA varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE PERMISSAO_AUD  WITH CHECK ADD  CONSTRAINT FKksidj8k966lryhg9l1t47hw00 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE PERMISSAO_AUD CHECK CONSTRAINT FKksidj8k966lryhg9l1t47hw00


CREATE TABLE PERFIL_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
	TIPO varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE PERFIL_AUD  WITH CHECK ADD  CONSTRAINT FK8mj42myd5ani3sgaffjiq3kj3 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE PERFIL_AUD CHECK CONSTRAINT FK8mj42myd5ani3sgaffjiq3kj3


CREATE TABLE PARAMETRO_SISTEMA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE PARAMETRO_SISTEMA_AUD  WITH CHECK ADD  CONSTRAINT FKdu1yw4asdrya3bw8f1ba1f93l FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE PARAMETRO_SISTEMA_AUD CHECK CONSTRAINT FKdu1yw4asdrya3bw8f1ba1f93l


CREATE TABLE NF_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_GERACAO date NULL,
	ID_CLIENTE int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE NF_AUD  WITH CHECK ADD  CONSTRAINT FKexsswbxnosxg7sp4evtvj3vll FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE NF_AUD CHECK CONSTRAINT FKexsswbxnosxg7sp4evtvj3vll


CREATE TABLE NATUREZA_OPERACAO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE NATUREZA_OPERACAO_AUD  WITH CHECK ADD  CONSTRAINT FKknkg5b8fsucg6sa3fr8ciob2x FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE NATUREZA_OPERACAO_AUD CHECK CONSTRAINT FKknkg5b8fsucg6sa3fr8ciob2x


CREATE TABLE MENSAGEM_DESTINATARIO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_LEITURA datetime2(7) NULL,
	PRIORITARIA varchar(255) NULL,
	SITUACAO varchar(255) NULL,
	ID_MENSAGEM int NULL,
	ID_USUARIO_DESTINO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE MENSAGEM_DESTINATARIO_AUD  WITH CHECK ADD  CONSTRAINT FK1wptuvk8kclxw81l24mx72fq8 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE MENSAGEM_DESTINATARIO_AUD CHECK CONSTRAINT FK1wptuvk8kclxw81l24mx72fq8


CREATE TABLE MENSAGEM_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ASSUNTO varchar(255) NULL,
	DATA datetime2(7) NULL,
	LEITURA_OBRIGATORIA varchar(255) NULL,
	TEXTO varchar(255) NULL,
	ID_USUARIO_ENVIO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE MENSAGEM_AUD  WITH CHECK ADD  CONSTRAINT FKofh59hykbbth4u7h993i5w1g8 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE MENSAGEM_AUD CHECK CONSTRAINT FKofh59hykbbth4u7h993i5w1g8


CREATE TABLE MENSAGEM_ANEXO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ID_MENSAGEM int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE MENSAGEM_ANEXO_AUD  WITH CHECK ADD  CONSTRAINT FKbf2p1taxmksfds0lnjt0ahpdw FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE MENSAGEM_ANEXO_AUD CHECK CONSTRAINT FKbf2p1taxmksfds0lnjt0ahpdw


CREATE TABLE LOGIN_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	LOGIN varchar(255) NULL,
	login_MOD bit NULL,
	SENHA varchar(255) NULL,
	senha_MOD bit NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE LOGIN_AUD  WITH CHECK ADD  CONSTRAINT FKp864iw35m9ff8jeukfwrwfe2d FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE LOGIN_AUD CHECK CONSTRAINT FKp864iw35m9ff8jeukfwrwfe2d


CREATE TABLE LOGIN_ACESSO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_ACESSO datetime2(7) NULL,
	ID_EMPRESA_TENAT int NULL,
	ID_LOGIN int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE LOGIN_ACESSO_AUD  WITH CHECK ADD  CONSTRAINT FK7w6w9ufa4rkvdsqftp1kdpbp6 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE LOGIN_ACESSO_AUD CHECK CONSTRAINT FK7w6w9ufa4rkvdsqftp1kdpbp6


CREATE TABLE GRUPO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
	GESTAO_INTERNA varchar(255) NULL,
	TIPO varchar(255) NULL,
	ID_USUARIO_RESPONSAVEL int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE GRUPO_AUD  WITH CHECK ADD  CONSTRAINT FKg3kvnk9a18b26x0ro02bie7w4 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE GRUPO_AUD CHECK CONSTRAINT FKg3kvnk9a18b26x0ro02bie7w4


CREATE TABLE FUNCAO_AJUDA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CHAVE varchar(255) NULL,
	DESCRICAO varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE FUNCAO_AJUDA_AUD  WITH CHECK ADD  CONSTRAINT FKhirypvstkt8wmcc5wh0fyne6q FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE FUNCAO_AJUDA_AUD CHECK CONSTRAINT FKhirypvstkt8wmcc5wh0fyne6q


CREATE TABLE FORNECEDOR_PRODUTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ATIVO varchar(2) NULL,
	ID_FORNECEDOR int NULL,
	ID_PRODUTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE FORNECEDOR_PRODUTO_AUD  WITH CHECK ADD  CONSTRAINT FKka8ug2vpm6c2a2eblc3hu57 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE FORNECEDOR_PRODUTO_AUD CHECK CONSTRAINT FKka8ug2vpm6c2a2eblc3hu57


CREATE TABLE FORNECEDOR_CONTATO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CAR varchar(50) NULL,
	EMAIL varchar(50) NULL,
	NOME varchar(200) NULL,
	TELEFONE varchar(50) NULL,
	ID_FORNECEDOR int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE FORNECEDOR_CONTATO_AUD  WITH CHECK ADD  CONSTRAINT FKqmm705iriue6txdt7tr4erw11 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE FORNECEDOR_CONTATO_AUD CHECK CONSTRAINT FKqmm705iriue6txdt7tr4erw11


CREATE TABLE FORNECEDOR_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	BAIRRO varchar(50) NULL,
	CELULAR varchar(50) NULL,
	CEP varchar(20) NULL,
	COMPLEMENTO varchar(100) NULL,
	CONTATO varchar(50) NULL,
	CPF_CNPJ varchar(30) NULL,
	EMAIL varchar(50) NULL,
	ENDERECO varchar(200) NULL,
	FONE_COMERCIAL varchar(50) NULL,
	FONE_RESIDENCIAL varchar(50) NULL,
	INSCRICAO_ESTADUAL varchar(50) NULL,
	INSCRICAO_MUNICIPAL varchar(50) NULL,
	NUMERO varchar(10) NULL,
	OBSERVACAO varchar(500) NULL,
	RAZAO_SOCIAL varchar(50) NULL,
	TIPO_PESSOA varchar(1) NULL,
	ID_CIDADE int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE FORNECEDOR_AUD  WITH CHECK ADD  CONSTRAINT FK1grm27dv6ku6s56gsuur4m59v FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE FORNECEDOR_AUD CHECK CONSTRAINT FK1grm27dv6ku6s56gsuur4m59v


CREATE TABLE EXTRATO_CONTA_CORRENTE_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	SALDO float NULL,
	SALDO_ANTERIOR float NULL,
	tipo varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE EXTRATO_CONTA_CORRENTE_AUD  WITH CHECK ADD  CONSTRAINT FKgwb97vdlvvrutncf3p994hmnt FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE EXTRATO_CONTA_CORRENTE_AUD CHECK CONSTRAINT FKgwb97vdlvvrutncf3p994hmnt


CREATE TABLE ESTOQUE_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA datetime2(7) NULL,
	QUANTIDADE int NULL,
	SALDO float NULL,
	SALDO_ANTERIOR float NULL,
	TIPO_OPERACAO float NULL,
	ID_COMPRA_PRODUTO int NULL,
	ID_PRODUTO int NULL,
	ID_VENDA_PRODUTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE ESTOQUE_AUD  WITH CHECK ADD  CONSTRAINT FKj9hxpfypiry96qyt1xpcakui FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE ESTOQUE_AUD CHECK CONSTRAINT FKj9hxpfypiry96qyt1xpcakui


CREATE TABLE EMPRESA_TENAT_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CODI_ORGAO varchar(255) NULL,
	DESCRICAO varchar(255) NULL,
	IMAGEM_MARCA_DAGUA varbinary(max) NULL,
	LO varbinary(max) NULL,
	TENAT varchar(255) NULL,
	TIPO varchar(255) NULL,
	USA_MARCA_CONTRACHEQUE varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
) 


ALTER TABLE EMPRESA_TENAT_AUD  WITH CHECK ADD  CONSTRAINT FKi8nx8tjccf165pn77o2o0avoa FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE EMPRESA_TENAT_AUD CHECK CONSTRAINT FKi8nx8tjccf165pn77o2o0avoa


CREATE TABLE EMPRESA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ATIVO varchar(255) NULL,
	BAIRRO varchar(255) NULL,
	CEP varchar(255) NULL,
	CIDADE varchar(255) NULL,
	CNPJ varchar(255) NULL,
	DESCRICAO varchar(255) NULL,
	EMAIL varchar(255) NULL,
	ENDERECO varchar(255) NULL,
	FONE varchar(255) NULL,
	RESPONSAVEL varchar(255) NULL,
	TENANT varchar(255) NULL,
	TIPO varchar(255) NULL,
	UF varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE EMPRESA_AUD  WITH CHECK ADD  CONSTRAINT FK6lxxa9d60lermh5aurmi024pb FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE EMPRESA_AUD CHECK CONSTRAINT FK6lxxa9d60lermh5aurmi024pb


CREATE TABLE DOCUMENTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE DOCUMENTO_AUD  WITH CHECK ADD  CONSTRAINT FK4rrkenmx4ekky7d6ev6i4m06o FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE DOCUMENTO_AUD CHECK CONSTRAINT FK4rrkenmx4ekky7d6ev6i4m06o


CREATE TABLE DOCUMENTO_ANEXO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	ARQUIVO varbinary(255) NULL,
	ID_DOCUMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)



ALTER TABLE DOCUMENTO_ANEXO_AUD  WITH CHECK ADD  CONSTRAINT FKk74p0wpvw6b58cstt2djwoljl FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE DOCUMENTO_ANEXO_AUD CHECK CONSTRAINT FKk74p0wpvw6b58cstt2djwoljl



CREATE TABLE CONTROLE_ACESSO_IP_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
	FAIXA_FINAL varchar(255) NULL,
	FAIXA_INICIAL varchar(255) NULL,
	TIPO varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTROLE_ACESSO_IP_AUD  WITH CHECK ADD  CONSTRAINT FKcxyuy011bu4qfq235j8jsrcph FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTROLE_ACESSO_IP_AUD CHECK CONSTRAINT FKcxyuy011bu4qfq235j8jsrcph


CREATE TABLE CONTA_RECEBER_PARCELA_PARCIAL_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_PAGAMENTO date NULL,
	VALOR_PA float NULL,
	ID_CONTA_RECEBER_PARCELA int NULL,
	ID_TIPO_PAGAMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL_AUD  WITH CHECK ADD  CONSTRAINT FK5kcvfuepvgqa7hlofo480e4eu FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

ALTER TABLE CONTA_RECEBER_PARCELA_PARCIAL_AUD CHECK CONSTRAINT FK5kcvfuepvgqa7hlofo480e4eu


CREATE TABLE CONTA_RECEBER_PARCELA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_RECEBIMENTO date NULL,
	DATA_VENCIMENTO date NULL,
	DESCONTO float NULL,
	JUROS float NULL,
	NUM_PARCELA int NULL,
	OBSERVACAO varchar(50) NULL,
	OUTROS_CUSTOS float NULL,
	SITUACAO varchar(255) NULL,
	VALOR_PARCELA float NULL,
	VALOR_RECEBIDO float NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_CONTA_RECEBER int NULL,
	ID_DOCUMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE CONTA_RECEBER_PARCELA_AUD  WITH CHECK ADD  CONSTRAINT FKkujahbaf0e2hjkhvqg822g062 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_RECEBER_PARCELA_AUD CHECK CONSTRAINT FKkujahbaf0e2hjkhvqg822g062


CREATE TABLE CONTA_RECEBER_PAGAMENTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	VALOR float NULL,
	ID_CONTA_RECEBER int NULL,
	ID_TIPO_PAGAMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTA_RECEBER_PAGAMENTO_AUD  WITH CHECK ADD  CONSTRAINT FKipmgb4o0uk5s67jahqgu928np FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_RECEBER_PAGAMENTO_AUD CHECK CONSTRAINT FKipmgb4o0uk5s67jahqgu928np


CREATE TABLE CONTA_RECEBER_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_RECEBIMENTO date NULL,
	DATA_VENCIMENTO date NULL,
	DESCONTO float NULL,
	DESCRICAO varchar(200) NULL,
	JUROS float NULL,
	NUM_PARCELA int NULL,
	OBSERVACAO varchar(500) NULL,
	OUTROS_CUSTOS float NULL,
	SITUACAO varchar(255) NULL,
	VALOR float NULL,
	VALOR_RECEBIDO float NULL,
	ID_CATERIA int NULL,
	ID_CENTRO_CUSTO int NULL,
	ID_CLIENTE int NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_DOCUMENTO int NULL,
	ID_VENDA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTA_RECEBER_AUD  WITH CHECK ADD  CONSTRAINT FKyk92i2hmj1ove3f7eq482xt2 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_RECEBER_AUD CHECK CONSTRAINT FKyk92i2hmj1ove3f7eq482xt2


CREATE TABLE CONTA_PAGAR_PARCELA_PARCIAL_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_PAGAMENTO date NULL,
	DATA_VENCIMENTO date NULL,
	ENCARS float NULL,
	JUROS float NULL,
	MULTA float NULL,
	NUM_PARCELA int NULL,
	SITUACAO varchar(255) NULL,
	VALOR float NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_CONTA_PAGAR_PARCELA int NULL,
	ID_DOCUMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL_AUD  WITH CHECK ADD  CONSTRAINT FK3jtrkrdueo5legetbium45uvn FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_PAGAR_PARCELA_PARCIAL_AUD CHECK CONSTRAINT FK3jtrkrdueo5legetbium45uvn


CREATE TABLE CONTA_PAGAR_PARCELA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_PAGAMENTO date NULL,
	DATA_VENCIMENTO date NULL,
	ENCARS float NULL,
	JUROS float NULL,
	MULTA float NULL,
	NUM_PARCELA int NULL,
	SITUACAO varchar(255) NULL,
	VALOR float NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_CONTA_PAGAR int NULL,
	ID_DOCUMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE CONTA_PAGAR_PARCELA_AUD  WITH CHECK ADD  CONSTRAINT FK44jcpjw968ucp273vyqbkt0fh FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_PAGAR_PARCELA_AUD CHECK CONSTRAINT FK44jcpjw968ucp273vyqbkt0fh


CREATE TABLE CONTA_PAGAR_PAGAMENTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	FORMA_PAGAMENTO varchar(100) NULL,
	VALOR float NULL,
	ID_FORNECEDOR int NULL,
	ID_TIPO_PAGAMENTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CONTA_PAGAR_PAGAMENTO_AUD  WITH CHECK ADD  CONSTRAINT FKs1k1bovlvork5oauiw3u3y5sj FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_PAGAR_PAGAMENTO_AUD CHECK CONSTRAINT FKs1k1bovlvork5oauiw3u3y5sj


CREATE TABLE CONTA_PAGAR_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_VENCIMENTO date NULL,
	DESCRICAO varchar(200) NULL,
	ENCARS float NULL,
	JUROS float NULL,
	MULTA_ATRASO float NULL,
	NUM_PARCELA int NULL,
	OBSERVACAO varchar(200) NULL,
	SITUACAO varchar(255) NULL,
	VALOR_TOTAL float NULL,
	ID_CATERIA int NULL,
	ID_CENTRO_CUSTO int NULL,
	ID_COMPRA int NULL,
	ID_CONTA_BANCARIA int NULL,
	ID_DOCUMENTO int NULL,
	ID_FORNECEDOR int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE CONTA_PAGAR_AUD  WITH CHECK ADD  CONSTRAINT FKd6pr0q80sn049n4pr2hfh248b FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_PAGAR_AUD CHECK CONSTRAINT FKd6pr0q80sn049n4pr2hfh248b


CREATE TABLE CONTA_BANCARIA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	ID_BANCO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE CONTA_BANCARIA_AUD  WITH CHECK ADD  CONSTRAINT FKbcdta65t7glbvc8i9c5a7udbc FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CONTA_BANCARIA_AUD CHECK CONSTRAINT FKbcdta65t7glbvc8i9c5a7udbc


CREATE TABLE COMPRA_PRODUTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	QUANTIDADE int NULL,
	VALOR float NULL,
	ID_COMPRA int NULL,
	ID_FORNECEDOR int NULL,
	ID_PRODUTO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE COMPRA_PRODUTO_AUD  WITH CHECK ADD  CONSTRAINT FKdlbllwus0x9ayttx7w78wab6x FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE COMPRA_PRODUTO_AUD CHECK CONSTRAINT FKdlbllwus0x9ayttx7w78wab6x


CREATE TABLE COMPRA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DATA_COMPRA datetime2(7) NULL,
	QTD_PARCELAS int NULL,
	VALOR_TOTAL float NULL,
	ID_COMPRADOR int NULL,
	ID_CONTA_BANCARIA int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE COMPRA_AUD  WITH CHECK ADD  CONSTRAINT FKo4oa44gjl2lrl5mqxo76f432f FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE COMPRA_AUD CHECK CONSTRAINT FKo4oa44gjl2lrl5mqxo76f432f


CREATE TABLE CLIENTE_CONTATO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CAR varchar(50) NULL,
	EMAIL varchar(50) NULL,
	NOME varchar(200) NULL,
	TELEFONE varchar(50) NULL,
	ID_CLIENTE int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CLIENTE_CONTATO_AUD  WITH CHECK ADD  CONSTRAINT FKa51quegyuac2054jp8b57ldyt FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CLIENTE_CONTATO_AUD CHECK CONSTRAINT FKa51quegyuac2054jp8b57ldyt

CREATE TABLE CLIENTE_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CEP varchar(15) NULL,
	COMPLEMENTO varchar(200) NULL,
	CPF_CNPJ varchar(200) NULL,
	EMAIL varchar(50) NULL,
	ENDERECO varchar(200) NULL,
	INDICADOR_INSCRICAO_ESTADUAL varchar(2) NULL,
	INSCRICAO_ESTADUAL varchar(50) NULL,
	INSCRICAO_MUNICIPAL varchar(50) NULL,
	NOME varchar(200) NULL,
	NUMERO varchar(50) NULL,
	OPTA_SIMPLES varchar(1) NULL,
	RAZAO_SOCIAL varchar(200) NULL,
	TELEFONE_CELULAR varchar(50) NULL,
	TELEFONE_COMERCIAL varchar(50) NULL,
	TELEFONE_RESIDENCIAL varchar(50) NULL,
	TEM_INSCRICAO_ESTADUAL varchar(1) NULL,
	TIPO varchar(2) NULL,
	ID_CIDADE int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CLIENTE_AUD  WITH CHECK ADD  CONSTRAINT FKmb04f54314oluucvkvw2kbd67 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CLIENTE_AUD CHECK CONSTRAINT FKmb04f54314oluucvkvw2kbd67


CREATE TABLE CIDADE_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	ID_UF int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)



ALTER TABLE CIDADE_AUD  WITH CHECK ADD  CONSTRAINT FK9n2n3jata1hfumlmf8w7670q4 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)

ALTER TABLE CIDADE_AUD CHECK CONSTRAINT FK9n2n3jata1hfumlmf8w7670q4


CREATE TABLE CENTRO_CUSTO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(255) NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CENTRO_CUSTO_AUD  WITH CHECK ADD  CONSTRAINT FKi92gfyu22il6j6abaojw4jfno FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CENTRO_CUSTO_AUD CHECK CONSTRAINT FKi92gfyu22il6j6abaojw4jfno


CREATE TABLE CATEGORIA_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	TIPO bit NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)


ALTER TABLE CATEGORIA_AUD  WITH CHECK ADD  CONSTRAINT FK7n9vhrjcew3qa0vhq418sy9a9 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE CATEGORIA_AUD CHECK CONSTRAINT FK7n9vhrjcew3qa0vhq418sy9a9



CREATE TABLE BANCO_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	DESCRICAO varchar(200) NULL,
	NUMERO int NULL,
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE BANCO_AUD  WITH CHECK ADD  CONSTRAINT FKsefddoprwoibmhuuj4j6qn2 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE BANCO_AUD CHECK CONSTRAINT FKsefddoprwoibmhuuj4j6qn2


CREATE TABLE NCM_AUD(
	ID int NOT NULL,
	REV int NOT NULL,
	REVTYPE smallint NULL,
	CODIGO int NULL,
	DESCRICAO varchar(500) NULL,
	ALIQUOTA_NACIONAL numeric(10,2),
	ALIQUOTA_IMPORTADO numeric(10,2),
	EX int,
	NCM_NBS varchar(1)
PRIMARY KEY CLUSTERED 
(
	ID ASC,
	REV ASC
)
)

ALTER TABLE NCM_AUD  WITH CHECK ADD  CONSTRAINT FKsefddoprwoibmhuuj4j2323 FOREIGN KEY(REV)
REFERENCES REVINFO (REVTYPE)


ALTER TABLE NCM_AUD CHECK CONSTRAINT FKsefddoprwoibmhuuj4j2323

