package br.com.villefortconsulting.sgfinancas.util;

import java.util.Arrays;
import javax.inject.Named;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
@Named
public enum EnumFuncaoAjuda {

    CADASTRO_PRODUTO("CAD_PRODUTO"),
    CADASTRO_SERVICO("CAD_SERVICO"),
    CADASTRO_CLIENTE("CAD_CLIENTE"),
    CADASTRO_TRANSPORTADORA("CAD_TRANSPORTADORA"),
    CADASTRO_BANCO("CAD_BANCO"),
    CADASTRO_CATEGORIA("CAD_CATEGORIA"),
    CADASTRO_TIPOPAGAMENTO("CAD_TIPO_PAGAMENTO"),
    CADASTRO_CENTRO_CUSTO("CAD_CENTRO_CUSTO"),
    CADASTRO_NATUREZA_OPERACAO("CAD_NATUREZA_OPERACAO"),
    CADASTRO_UNIDADE_MEDIDA("CAD_UNI_MEDIDA"),
    CADASTRO_CONTA_BANCARIA("CAD_CONTA_BANCARIA"),
    CADASTRO_FORNECEDOR("CAD_FORNECEDOR"),
    CADASTRO_CONTA_RECEBER("CAD_CONTA_RECEBER"),
    CADASTRO_SITUACAO_TRIBUTARIA("CAD_SITAUCAO_TRIBUTARIA"),
    CADASTRO_EMPRESA("CAD_EMPRESA"),
    CADASTRO_ORIGEM_MERCADORIA("CAD_ORIGEM_MERCADORIA"),
    CADASTRO_CONTAS_PAGAR("CAD_CONTAS_PAGAR"),
    CADASTRO_NOTA_FISCAL_SERVICO("CAD_NF_SERVICO"),
    CADASTRO_NOTA_FISCAL_PRODUTO("CAD_NF_PRODUTO"),
    CADASTRO_PAGAR_CONTA_PARCELA_PARCIAL("CAD_PAGAR_CONTA_PARCELA_PARCIAL"),
    CADASTRO_CONTA_RECEBER_PARCELA_PARCIAL("CAD_CONTA_RECEBER_PARCELA_PARCIAL"),
    CADASTRO_VENDA("CAD_VENDA"),
    CADASTRO_COMPRA("CAD_COMPRA"),
    CADASTRO_COMPRA_PDV("CAD_COMPRA_PDV"),
    CADASTRO_ARQUIVO_IMPORTACAO("CAD_ARQUIVO_IMPORTACAO"),
    CANCELAMENTO_PARCELA_RECEBER("CAN_CONTA_RECEBER_PARCELA"),
    CANCELAMENTO_PARCELA_PAGAR("CAN_CONTA_PAGAR_PARCELA"),
    CADASTRO_MENSALIDADE("CAD_MENSALIDADE"),
    CADASTRO_LANCAMENTO("CAD_LANCAMENTO"),
    CADASTRO_CONTRATO_ENTRADA("CAD_CONTRATO_ENTRADA"),
    CADASTRO_FUNCIONARIO("CAD_FUNCIONARIO"),
    AJUSTE_CONTRATO_CLIENTE("AJU_CONTRATO_CLIENTE"),
    AJUSTE_CONTRATO_FORNECEDOR("AJU_CONTRATO_FORNECEDOR"),
    CADASTRO_AREA_ATUACAO("CAD_AREA_ATUACAO"),
    CADASTRO_PROFESSOR("CAD_PROFESSOR"),
    CADASTRO_TURMA("CAD_TURMA"),
    CADASTRO_OS("CAD_OS");

    private final String chave;

    public static EnumFuncaoAjuda retornaEnumSelecionado(String enumSelecionado) {
        return Arrays.asList(values()).stream()
                .filter(item -> item.chave.contains(enumSelecionado))
                .findAny()
                .orElse(null);
    }

}
